const DashboardActionTypes = {
    LOAD_REVENUE_COLLECTION: 'LOAD_REVENUE_COLLECTION',
    LOAD_REVENUE_COLLECTION_FAILURE: 'LOAD_REVENUE_COLLECTION_FAILURE',
    SET_REVENUE_COLLECTION: 'SET_REVENUE_COLLECTION',
    DOWNLOAD_ZONE_DATA: 'DOWNLOAD_ZONE_DATA',
    DOWNLOAD_SA_DATA: 'DOWNLOAD_SA_DATA',
    DOWNLOAD_SA_READINGS_IN_MONTH: 'DOWNLOAD_SA_READINGS_IN_MONTH'
}

export default DashboardActionTypes;